FROM pytorch/pytorch:latest

RUN apt update && apt -y install git && pip install datasets evaluate transformers huggingface_hub accelerate ipywidgets  scikit-learn plotly python-dotenv sentence-transformers langchain